language: minimal

matrix:
  include:
  - os: linux  # 2015
    env: PYTHON_VERSION="3.5" DEPS="numpy=1.10 geos=3.5 pyproj=2.1"
  - os: linux  # 2017
    env: PYTHON_VERSION="3.6" DEPS="numpy=1.13 geos=3.6 pyproj"
  - os: linux  # now
    env: PYTHON_VERSION="3.7" DEPS="numpy geos pyproj"
  - os: osx
    env: PYTHON_VERSION="3.7" DEPS="numpy geos pyproj"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH"
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r;
  - conda update --yes conda;
  - conda config --set changeps1 no --set restore_free_channel true;
  - conda create -n testenv --yes python=$PYTHON_VERSION $DEPS pytest;
  - conda activate testenv;
  - conda --version ; python --version ; pip --version;
  - python setup.py build_ext --inplace
  - pip install . --no-deps

script:
  - if [[ "$PYTHON_VERSION" == "3.5" ]];
    then pytest;
    else pytest --doctest-modules;
    fi;
